### ISSUE TITLE
Archive this?

### ISSUE THREAD

**Issue by phoebe-leong** [Kimitzuni/bsh#1]
In the demon core repository you stated this as the old repository for bsh.
If development on this has moved to the demon core repo, which I'm assuming it has, shouldn't this repository be archived or something?

**Comment by phoebe-leong** [comment]
Then again you updated this five days ago..

**Comment by Kimitzuni** [comment]
This /is/ the old repo for it, but is still here because in the case people just want bsh and not the other stuff
